### ISSUE TITLE
Update. Captain remove player from team

### ISSUE THREAD

**Issue by Sttpwilson** [simon-kyger/brawlhallacrewbattles#8]
Coming soon

**Comment by simon-kyger** [comment]
This feature would require a rewrite of updategame() method on server.

**Comment by Sttpwilson** [comment]
On it HOMIE

**Comment by simon-kyger** [comment]
Captain can't remove themselves so there has to be a check for that.

If captain removes a member from their team, they'd need to have 2 consecutive picks, or possibly more if they removed more than 1 person, which means the pick phase needs to have a counter for the individual captains.

**Comment by simon-kyger** [comment]
Finished in v1.2.8

**Comment by simon-kyger** [comment]
Current state:

changed handling with how updategames works. 
admins now have complete authority to move whenever, even if they are a captain.
captains now have authority to move players at will without a picking phase  but they are limited to only their team and inbound fields to move to or from.
if a captain is removed by the admin, the next person on the team listed becomes the captain, in a stack sorta style. this is also the behavior if a captain leaves a game or disconnects.
if the admin removes all players from a team, captains are disabled until admin places at least one person on each team.
reset game also was updated to accomodate all these changes, so that still works too. 
if the admin disconnects, the entire game is destroyed and all users are kicked back to the create/join page.
